# Copyright 2021-2023 David Robillard <d@drobilla.net>
# SPDX-License-Identifier: 0BSD OR ISC

variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  image: lv2plugin/debian-x64
  script:
    - meson setup build -Dwerror=true
    - ninja -C build test

dev:
  image: lv2plugin/debian-x64
  script:
    - meson setup build -Dbuildtype=debug -Dwarning_level=3 -Dwerror=true -Db_coverage=true -Ddefault_library=both -Dprefix=/
    - ninja -C build test
    - ninja -C build coverage-html
    - DESTDIR=$(pwd)/build/dest meson install -C build
    - meson configure -Dbuildtype=release -Db_coverage=false -Dprefix=/ build
    - ninja -C build test
  coverage: '/ *lines\.*: \d+\.\d+.*/'
  artifacts:
    paths:
      - build/dest
      - build/meson-logs/coveragereport

static:
  image: lv2plugin/debian-x64
  script:
    - meson setup build -Ddefault_library=static -Dwarning_level=3 -Dwerror=true
    - ninja -C build test

sanitize:
  image: lv2plugin/debian-x64-clang
  script:
    - meson setup build -Db_lundef=false -Dbuildtype=plain -Dwarning_level=3 -Dwerror=true -Dc_args="-fno-sanitize-recover=all -fsanitize=address -fsanitize=undefined -fsanitize=float-divide-by-zero -fsanitize=implicit-conversion -fsanitize=local-bounds -fsanitize=nullability" -Dc_link_args="-fno-sanitize-recover=all -fsanitize=address -fsanitize=undefined -fsanitize=float-divide-by-zero -fsanitize=implicit-conversion -fsanitize=local-bounds -fsanitize=nullability"
    - ninja -C build test
    - meson configure build -Dbuildtype=debugoptimized -Dc_args="" -Dc_link_args=""
    - meson configure build -Db_sanitize=thread
    - ninja -C build test
    - meson configure build -Db_sanitize=memory
    - ninja -C build test
  variables:
    CC: "clang"

# Linux Distributions

fedora:
  image: lv2plugin/fedora-dev
  script:
    - meson setup build -Dbuildtype=plain -Dwarning_level=3 -Dwerror=true
    - ninja -C build test
  variables:
    CFLAGS: -O2 -D_FORTIFY_SOURCE=2

# Linux Platforms

arm32:
  image: lv2plugin/debian-arm32
  script:
    - meson setup build --cross-file=/usr/share/meson/cross/arm-linux-gnueabihf.ini -Dbuildtype=debug -Dwarning_level=3 -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

arm64:
  image: lv2plugin/debian-arm64
  script:
    - meson setup build --cross-file=/usr/share/meson/cross/aarch64-linux-gnu.ini -Dbuildtype=debug -Dwarning_level=3 -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

x32:
  image: lv2plugin/debian-x32
  script:
    - meson setup build --cross-file=/usr/share/meson/cross/i686-linux-gnu.ini -Dbuildtype=debug -Dwarning_level=3 -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

mingw32:
  image: lv2plugin/debian-mingw32
  script:
    - meson setup build --cross-file=/usr/share/meson/cross/i686-w64-mingw32.ini -Dc_args="-static-libgcc" -Dc_link_args="-static-libgcc" -Dbuildtype=debug -Dwarning_level=everything -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test
  variables:
    WINEPATH: "Z:\\usr\\lib\\gcc\\i686-w64-mingw32\\10-win32"

mingw64:
  image: lv2plugin/debian-mingw64
  script:
    - meson setup build --cross-file=/usr/share/meson/cross/x86_64-w64-mingw32.ini -Dc_args="-static-libgcc" -Dc_link_args="-static-libgcc" -Dbuildtype=debug -Dwarning_level=everything -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test
  variables:
    WINEPATH: "Z:\\usr\\lib\\gcc\\x86_64-w64-mingw32\\10-win32;Z:\\builds\\drobilla\\sajs\\build"

wasm:
  image: lv2plugin/debian-wasm
  script:
    - meson setup build --cross-file=/usr/share/meson/cross/wasm.ini -Dbuildtype=debug -Dwarning_level=3 -Dwerror=true -Ddefault_library=static
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

# Non-Linux/Docker rows (not hosted)

freebsd:
  tags: [freebsd,meson]
  script:
    - meson setup build -Dbuildtype=debug -Dwarning_level=everything -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

mac:
  tags: [macos]
  script:
    - meson setup build -Dbuildtype=debug -Dwarning_level=3 -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

win:
  tags: [windows,meson]
  script:
    - meson setup build -Dbuildtype=debug -Dwarning_level=everything -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

# Documentation

pages:
  stage: deploy
  script:
    - mv build/meson-logs/coveragereport/ .public/coverage
    - mv .public public
  needs:
    - dev
  artifacts:
    paths:
      - public
  only:
    - main
